version: "3"

services:
  php-app:
    build:
      context: .
    ports:
      - "8080:80"

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: owasp_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: owasp-1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "8079:80"
    depends_on:
      - mysql

volumes:
  mysql_data: